# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

target 'SimpleConverter' do
pod 'AFNetworking', '~> 2.5'
pod 'Reachability', '~> 3.2'
pod 'TBStateMachine', '~> 3.0'
pod 'dhd-objc-utils', :podspec => 'https://raw.github.com/risik/dhd-objc-utils/master/dhd-objc-utils.podspec'
end

target 'SimpleConverterTests' do

end

